export enum ConquestKey {
  FIRST_VISIT = 'FIRST_VISIT',
  VISITED_5_PARKS = 'VISITED_5_PARKS',
  VISITED_10_PARKS = 'VISITED_10_PARKS',
  VISITED_25_PARKS = 'VISITED_25_PARKS',
  FIRST_FAVORITE = 'FIRST_FAVORITE',
  FAVORITED_5_PARKS = 'FAVORITED_5_PARKS',
  FIRST_REVIEW = 'FIRST_REVIEW',
  REVIEWED_5_PARKS = 'REVIEWED_5_PARKS',
  VISITED_3_CITIES = 'VISITED_3_CITIES',
  ALL_ROUNDER = 'ALL_ROUNDER',
}
